from fpdf import FPDF
from services.database import DocumentMetadata
import json
from datetime import datetime

class PDFReport(FPDF):
    def header(self):
        # Logo placeholder or Title
        self.set_font("helvetica", "B", 20)
        self.set_text_color(40, 40, 150) # Dark Blue
        self.cell(0, 15, "ExplainO - Document Analysis Report", ln=True, align="C")
        self.ln(5)
        self.set_draw_color(40, 40, 150)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Generated by ExplainO on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} - Page {self.page_no()}", align="C")

def safe_text(text: str) -> str:
    """Ensure text is compatible with standard FPDF fonts (Latin-1)."""
    if not text: return ""
    # Replace common problematic characters or just encode/decode to strip them
    return text.encode('latin-1', 'replace').decode('latin-1')

def generate_pdf_report(doc: DocumentMetadata) -> bytes:
    pdf = PDFReport()
    pdf.add_page()
    
    # 1. Filename & Basic Info
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, safe_text(f"Document: {doc.filename}"), ln=True)
    pdf.set_font("helvetica", "", 10)
    pdf.cell(0, 8, safe_text(f"Uploaded: {doc.upload_time.strftime('%Y-%m-%d')}"), ln=True)
    pdf.ln(5)

    # 2. Executive Summary
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(40, 40, 150)
    pdf.cell(0, 10, "Executive Summary", ln=True)
    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(0, 0, 0)
    pdf.multi_cell(0, 7, safe_text(doc.explanation) or "No summary available.")
    pdf.ln(10)

    # 3. Key Insights (JSON)
    if doc.points_json:
        points = json.loads(doc.points_json)
        if points:
            pdf.set_font("helvetica", "B", 12)
            pdf.set_text_color(40, 40, 150)
            pdf.cell(0, 10, "Key Insights & Factual Points", ln=True)
            pdf.set_font("helvetica", "", 10)
            pdf.set_text_color(0, 0, 0)
            for point in points:
                pdf.multi_cell(0, 7, safe_text(f"- {point}"))
            pdf.ln(10)

    # 4. Potential Risks
    if doc.risks_json:
        risks = json.loads(doc.risks_json)
        if risks:
            pdf.set_font("helvetica", "B", 12)
            pdf.set_text_color(200, 50, 50) # Red
            pdf.cell(0, 10, "Potential Risks & Warnings", ln=True)
            pdf.set_font("helvetica", "", 10)
            pdf.set_text_color(0, 0, 0)
            for risk in risks:
                pdf.multi_cell(0, 7, safe_text(f"[!] {risk}"))
            pdf.ln(10)

    # 5. Important Dates
    if doc.dates_json:
        dates = json.loads(doc.dates_json)
        if dates:
            pdf.set_font("helvetica", "B", 12)
            pdf.set_text_color(100, 100, 100) # Gray
            pdf.cell(0, 10, "Deadlines & Critical Dates", ln=True)
            pdf.set_font("helvetica", "", 10)
            pdf.set_text_color(0, 0, 0)
            for d in dates:
                pdf.multi_cell(0, 7, safe_text(f"> {d}"))
            pdf.ln(10)

    # In fpdf2, output() returns bytes by default if no filename is provided
    return pdf.output()
